backend:
  name: git-gateway
  branch: main

# Media files configuration
media_folder: "static/images" # Media files will be stored here
public_folder: "/images" # The src attribute for uploaded media

collections:
  - name: "coaches"
    label: "Coaches"
    files:
      - file: "data/coaches.yaml"
        label: "Coaches List"
        name: "coaches-list"
        fields:
          - label: "Coaches"
            name: "coaches"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Image", name: "image", widget: "string"}
              - {label: "Bio", name: "bio", widget: "text"}

  - name: "players"
    label: "Players"
    files:
      - file: "data/players.yaml"
        label: "Players List"
        name: "players-list"
        fields:
          - label: "Teams"
            name: "teams"
            widget: "list"
            fields:
              - {label: "Team Name", name: "name", widget: "string"}
              - label: "Players"
                name: "players"
                widget: "list"
                fields:
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "Position", name: "position", widget: "string"}
                  - {label: "Height", name: "height", widget: "string"}
                  - {label: "Image", name: "image", widget: "string"}
                  - {label: "Bio", name: "bio", widget: "text"} 