backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "coaches"
    label: "Coaches"
    file: "data/coaches.yaml"
    description: "Coaches information"
    fields:
      - name: "coaches"
        label: "Coaches"
        widget: "list"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Image", name: "image", widget: "image", required: false, default: "https://placehold.co/100x100/png"}
          - {label: "Bio", name: "bio", widget: "text"}

  - name: "players"
    label: "Players"
    file: "data/players.yaml"
    description: "Players information"
    fields:
      - name: "teams"
        label: "Teams"
        widget: "list"
        fields:
          - {label: "Team Name", name: "name", widget: "string"}
          - name: "players"
            label: "Players"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Position", name: "position", widget: "string"}
              - {label: "Height", name: "height", widget: "string"}
              - {label: "Image", name: "image", widget: "image", required: false, default: "https://placehold.co/80x80/png"}
              - {label: "Bio", name: "bio", widget: "text"} 