backend:
  name: git-gateway
  branch: main

# Media files configuration
media_folder: "static/images" # Media files will be stored here
public_folder: "/images" # The src attribute for uploaded media

# Enable editorial workflow for better content management
publish_mode: editorial_workflow

collections:
  - name: "test"
    label: "Test Collection"
    folder: "content/test"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

# Coaches collection
  - name: "coaches" # Used in routes, e.g., /admin/collections/coaches
    label: "Coaches" # Used in the UI
    files:
      - file: "data/coaches.yaml"
        label: "Coaches List"
        name: "coaches-list"
        preview: true
        fields:
          - label: "Coaches"
            name: "coaches"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Image", name: "image", widget: "string", hint: "URL to coach image"}
              - {label: "Bio", name: "bio", widget: "text"}

# Players collection
  - name: "players" # Used in routes, e.g., /admin/collections/players
    label: "Players" # Used in the UI
    files:
      - file: "data/players.yaml"
        label: "Players List"
        name: "players-list"
        preview: true
        fields:
          - label: "Teams"
            name: "teams"
            widget: "list"
            fields:
              - {label: "Team Name", name: "name", widget: "string"}
              - label: "Players"
                name: "players"
                widget: "list"
                fields:
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "Position", name: "position", widget: "string"}
                  - {label: "Height", name: "height", widget: "string"}
                  - {label: "Image", name: "image", widget: "string", hint: "URL to player image"}
                  - {label: "Bio", name: "bio", widget: "text"} 