backend:
  name: git-gateway
  branch: main

# Media files configuration
media_folder: "static/images" # Media files will be stored here
public_folder: "/images" # The src attribute for uploaded media

collections:
  - name: "coaches"
    label: "Coaches"
    files:
      - file: "data/coaches.yaml"
        label: "Coaches List"
        name: "coaches-list"
        fields:
          - label: "Coaches"
            name: "coaches"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Image", name: "image", widget: "string"}
              - {label: "Bio", name: "bio", widget: "text"}

  - name: "players"
    label: "Players"
    files:
      - file: "data/players.yaml"
        label: "Players List"
        name: "players-list"
        fields:
          - label: "Teams"
            name: "teams"
            widget: "list"
            fields:
              - {label: "Team Name", name: "name", widget: "string"}
              - label: "Players"
                name: "players"
                widget: "list"
                fields:
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "Position", name: "position", widget: "string"}
                  - {label: "Height", name: "height", widget: "string"}
                  - {label: "Image", name: "image", widget: "string"}
                  - {label: "Bio", name: "bio", widget: "text"}

  - name: "player_pages"
    label: "Player Pages"
    folder: "content/players"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Height", name: "height", widget: "string"}
      - {label: "Image", name: "image", widget: "string"}
      - {label: "Bio", name: "bio", widget: "text"}
      - {label: "Team", name: "team", widget: "select", options: ["17U", "16U"]}
      - label: "Videos"
        name: "videos"
        widget: "list"
        required: false
        field: 
          label: "YouTube Video URL"
          name: "video"
          widget: "string"
          hint: "Regular YouTube URLs like https://www.youtube.com/watch?v=dqkU8dvj_SY are supported"
      - label: "Stats"
        name: "stats"
        widget: "list"
        required: false
        fields:
          - {label: "Season", name: "season", widget: "string"}
          - {label: "Points Per Game", name: "ppg", widget: "number", value_type: "float"}
          - {label: "Rebounds Per Game", name: "rpg", widget: "number", value_type: "float"}
          - {label: "Assists Per Game", name: "apg", widget: "number", value_type: "float"}
          - {label: "Field Goal Percentage", name: "fgp", widget: "string"}
          - {label: "Three Point Percentage", name: "tpp", widget: "string"} 